
spring:
  application:
    name: api-one
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
            - ${azure.client-id}
          jwk-set-uri: https://${azure.tenant.name}.b2clogin.com/${azure.tenant.id}/discovery/v2.0/keys?p=${azure.user-flow-name}
  docker:
    compose:
      lifecycle-management: start_only
logging:
  group:
    persistence:
      - org.springframework.data.mongodb
      - org.springframework.data.mongodb.core
  level:
    root: info
    com.github.rubenqba.apione: debug
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core: DEBUG
#        boot.autoconfigure.security: DEBUG
#        security.oauth2: DEBUG
#        security.oauth2.client: DEBUG
#        security.oauth2.server.resource: DEBUG
