spring:
  application:
    name: api-azure
  config:
    import:
      - 'optional:configtree:/run/secrets/'
      - 'configserver:'
  cloud:
    config:
      uri: https://cc.dardeus.io/config
      fail-fast: true
      profile: ${spring.profiles.active}
  docker:
    compose:
      lifecycle-management: start_only
logging:
  group:
    persistence:
      - org.springframework.data.mongodb
      - org.springframework.data.mongodb.core
    security:
      - org.springframework.security
      - org.springframework.security.oauth2
      - org.springframework.security.oauth2.client
      - org.springframework.security.oauth2.server
      - org.springframework.security.web
      - org.springframework.security.config
  level:
    root: info
    com.github.rubenqba.apione: debug
    web: DEBUG
    persistence: off
    security: trace
